# Generated by Django 5.1.1 on 2024-10-08 14:13

import delivery_stock.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.BigIntegerField(unique=True)),
                ("date_recive", models.DateTimeField()),
                ("date_complite", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_prefix", models.CharField(blank=True, max_length=50)),
                (
                    "image_data",
                    models.ImageField(
                        upload_to=delivery_stock.models.custom_upload_path
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "work_zone",
                    models.IntegerField(
                        choices=[
                            (1, "Recive"),
                            (2, "Storage"),
                            (3, "Ready to load"),
                            (4, "Utilization"),
                            (4, "Shiped"),
                            (4, "Cancel"),
                            (4, "Transfer"),
                        ],
                        default=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReasoneComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reception",
                    models.CharField(
                        choices=[("first", "first"), ("second", "second")],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SuplierSKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.IntegerField()),
                ("deskription", models.CharField(max_length=200)),
                ("barcode", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SecondRecDelivery",
            fields=[
                (
                    "delivery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="delivery_stock.delivery",
                    ),
                ),
                (
                    "pre_advice_nr",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("master_nr", models.CharField(blank=True, max_length=40, null=True)),
                ("tir_nr", models.CharField(blank=True, max_length=40, null=True)),
            ],
            bases=("delivery_stock.delivery",),
        ),
        migrations.CreateModel(
            name="DeliveryContainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.BigIntegerField(unique=True)),
                ("lovo_link", models.TextField(blank=True, null=True)),
                ("lovo_name", models.TextField(blank=True, null=True)),
                ("date_complite", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_2r",
                        to="delivery_stock.location",
                    ),
                ),
                (
                    "recive_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recive_location_2r",
                        to="delivery_stock.location",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="delivery_stock.secondrecdelivery",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContainerLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reasone_comment", models.TextField()),
                ("qty_unit", models.IntegerField()),
                (
                    "recive_unit",
                    models.CharField(
                        choices=[
                            ("szt.", "szt."),
                            ("pall. mix.", "pall. mix."),
                            ("pall.full.", "pall.full."),
                            ("pacz.", "pacz."),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "not_sys_barcode",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="delivery_stock.deliverycontainer",
                    ),
                ),
                (
                    "suplier_sku",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="delivery_stock.supliersku",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("supplier_wms_id", models.CharField(max_length=40)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "supplier_wms_id"),
                        name="unique_supplier_wms_id",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="delivery",
            name="supplier_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="delivery_stock.supplier",
            ),
        ),
        migrations.CreateModel(
            name="FirstRecDelivery",
            fields=[
                (
                    "delivery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="delivery_stock.delivery",
                    ),
                ),
                ("qty_unit", models.IntegerField()),
                (
                    "recive_unit",
                    models.CharField(
                        choices=[
                            ("szt.", "szt."),
                            ("pall.", "pall"),
                            ("pacz.", "pacz."),
                        ],
                        max_length=10,
                    ),
                ),
                ("tir_nr", models.CharField(max_length=40)),
                (
                    "container_nr",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("reasone_comment", models.TextField()),
                (
                    "images_url",
                    models.ManyToManyField(blank=True, to="delivery_stock.imagemodel"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="delivery_stock.location",
                    ),
                ),
                (
                    "recive_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recive_location",
                        to="delivery_stock.location",
                    ),
                ),
            ],
            bases=("delivery_stock.delivery",),
        ),
    ]
