# Generated by Django 5.1.1 on 2024-09-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="lovo_link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="lovo_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
