# Generated by Django 5.1.1 on 2024-10-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="date_complite",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
