# Generated by Django 5.1.1 on 2024-10-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_stock", "0002_containerline_images_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="containerline",
            name="line_nr",
            field=models.IntegerField(default=1),
        ),
    ]
