# Generated by Django 5.1.1 on 2024-09-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_stock", "0002_delivery_lovo_link_delivery_lovo_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="suplier_sku",
            field=models.ManyToManyField(blank=True, to="delivery_stock.supliersku"),
        ),
    ]
