# Generated by Django 5.1.1 on 2024-10-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_stock", "0002_alter_delivery_date_complite"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="not_sys_barcode",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="master_nr",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
