# Generated by Django 5.1.1 on 2024-10-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_stock", "0003_delivery_suplier_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="complite_status",
            field=models.BooleanField(default=False),
        ),
    ]
