# Generated by Django 5.1.1 on 2024-10-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_stock", "0004_deliverycontainer_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverycontainer",
            name="transaction",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
