# Generated by Django 5.1.1 on 2024-10-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_stock", "0005_alter_deliverycontainer_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="containerline",
            name="alternative_product_name",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
